import { useState, useEffect } from 'react';
import { getMockDB } from '../../lib/supabaseClient';

const A = {
  bg: '#fff8f3',          // Sand background
  sidebar: '#faf2ec',     // Warm Cream
  surface: '#ffffff',
  primary: '#6f583c',     // Wood Brown
  accent: '#5f745d',      // Sage Green
  badgeBg: '#e8ede7',     // Sage Light
  border: '#d1c4b9',      // Border Brownish
  textPrimary: '#1e1b17', // Dark Wood
  textMuted: '#4e453c',   // Soft Wood / Muted Text
};

interface BackupEntry {
  id: string;
  name: string;
  size: string;
  date: string;
  type: 'full' | 'incremental';
  status: 'success' | 'failed' | 'in_progress';
  tables: number;
  records: number;
}

const MOCK_BACKUPS: BackupEntry[] = [
  { id: 'bk-9027', name: 'homestay_dorm_full_2026-06-01.sql', size: '3.8 MB', date: '01/06/2026 - 23:30', type: 'full', status: 'success', tables: 14, records: 2847 },
  { id: 'bk-9026', name: 'homestay_dorm_inc_2026-05-28.sql', size: '0.9 MB', date: '28/05/2026 - 18:00', type: 'incremental', status: 'success', tables: 8, records: 312 },
  { id: 'bk-9025', name: 'homestay_dorm_full_2026-05-15.sql', size: '3.5 MB', date: '15/05/2026 - 23:30', type: 'full', status: 'success', tables: 14, records: 2711 },
  { id: 'bk-9024', name: 'homestay_dorm_inc_2026-05-01.sql', size: '0.4 MB', date: '01/05/2026 - 14:00', type: 'incremental', status: 'failed', tables: 0, records: 0 },
  { id: 'bk-9023', name: 'homestay_dorm_full_2026-04-30.sql', size: '3.2 MB', date: '30/04/2026 - 23:30', type: 'full', status: 'success', tables: 14, records: 2588 },
];

export default function AdminBackupPage() {
  const [backups, setBackups] = useState<BackupEntry[]>(MOCK_BACKUPS);
  const [isCreating, setIsCreating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [progressStage, setProgressStage] = useState('');
  const [confirmRestore, setConfirmRestore] = useState<BackupEntry | null>(null);
  const [restoring, setRestoring] = useState(false);
  const [dbStats, setDbStats] = useState({ customers: 0, rooms: 0, contracts: 0, invoices: 0 });

  useEffect(() => {
    const db = getMockDB();
    setDbStats({
      customers: (db.customers || []).length,
      rooms: (db.rooms || []).length,
      contracts: (db.contracts || []).length,
      invoices: (db.invoices || []).length,
    });
  }, []);

  const startBackup = () => {
    if (isCreating) return;
    setIsCreating(true);
    setProgress(0);

    const stages = [
      { msg: 'Khởi tạo kết nối cơ sở dữ liệu...', pct: 10 },
      { msg: 'Xuất bảng customers và accounts...', pct: 25 },
      { msg: 'Xuất bảng rooms và contracts...', pct: 45 },
      { msg: 'Xuất bảng invoices và services...', pct: 65 },
      { msg: 'Xuất bảng assets và conditions...', pct: 80 },
      { msg: 'Nén file và tạo checksum SHA-256...', pct: 92 },
      { msg: 'Lưu trữ vào Local Storage...', pct: 100 },
    ];

    let stageIdx = 0;
    const timer = setInterval(() => {
      if (stageIdx >= stages.length) {
        clearInterval(timer);
        const now = new Date();
        const newBackup: BackupEntry = {
          id: `bk-${Math.floor(Math.random() * 9000) + 1000}`,
          name: `homestay_dorm_full_${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}.sql`,
          size: '4.1 MB',
          date: `${now.toLocaleDateString('vi-VN')} - ${now.toLocaleTimeString('vi-VN', { hour: '2-digit', minute: '2-digit' })}`,
          type: 'full',
          status: 'success',
          tables: 14,
          records: Object.values(dbStats).reduce((s, v) => s + v, 0),
        };
        setBackups(prev => [newBackup, ...prev]);
        setIsCreating(false);
        setProgress(0);
        setProgressStage('');
        return;
      }
      const stage = stages[stageIdx];
      setProgress(stage.pct);
      setProgressStage(stage.msg);
      stageIdx++;
    }, 600);
  };

  const doRestore = () => {
    if (!confirmRestore) return;
    setRestoring(true);
    setTimeout(() => {
      localStorage.removeItem('homestay_dorm_mock_db');
      setRestoring(false);
      setConfirmRestore(null);
      window.location.reload();
    }, 1500);
  };

  const downloadBackup = (b: BackupEntry) => {
    const db = getMockDB();
    const content = `-- HomeStay Dorm Backup\n-- Date: ${b.date}\n-- Generated by Admin Panel\n\n${JSON.stringify(db, null, 2)}`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = b.name;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-fade-in-up" style={{ fontFamily: 'Lexend, sans-serif' }}>
      {/* Header */}
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight" style={{ color: A.primary }}>Sao lưu & Khôi phục</h1>
          <p className="text-sm mt-1" style={{ color: A.textMuted }}>
            Quản lý sao lưu cơ sở dữ liệu và khôi phục hệ thống từ các bản backup đã tạo.
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => {
              if (window.confirm("Bạn có chắc chắn muốn khôi phục dữ liệu về ban đầu? Toàn bộ thay đổi của bạn sẽ bị xóa.")) {
                localStorage.removeItem('homestay_dorm_mock_db');
                window.location.reload();
              }
            }}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-[#BA1A1A] bg-[#FFDAD6] border border-[#BA1A1A]/20 hover:opacity-90 active:scale-95 cursor-pointer">
            <span className="material-symbols-outlined text-[18px]">restart_alt</span>
            Khôi phục dữ liệu gốc
          </button>
          <button
            onClick={startBackup}
            disabled={isCreating}
            className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold text-white shadow hover:opacity-90 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
            style={{ background: A.primary }}>
            <span className="material-symbols-outlined text-[18px]">
              {isCreating ? 'hourglass_top' : 'backup'}
            </span>
            {isCreating ? 'Đang sao lưu...' : 'Tạo sao lưu ngay'}
          </button>
        </div>
      </header>

      {/* Database Stats */}
      <section className="grid grid-cols-2 xl:grid-cols-4 gap-4">
        {[
          { icon: 'group', label: 'Khách hàng', val: dbStats.customers },
          { icon: 'meeting_room', label: 'Phòng', val: dbStats.rooms },
          { icon: 'description', label: 'Hợp đồng', val: dbStats.contracts },
          { icon: 'receipt', label: 'Hóa đơn', val: dbStats.invoices },
        ].map((item, i) => (
          <div key={i} className="rounded-xl p-5 flex flex-col gap-3"
            style={{ background: A.surface, border: `1px solid ${A.border}`, boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
            <div className="p-2 rounded-lg w-fit" style={{ background: A.badgeBg, color: A.accent }}>
              <span className="material-symbols-outlined text-xl">{item.icon}</span>
            </div>
            <div>
              <p className="text-sm font-medium" style={{ color: A.textMuted }}>{item.label}</p>
              <p className="text-3xl font-bold" style={{ color: A.primary }}>{item.val} bản ghi</p>
            </div>
          </div>
        ))}
      </section>

      {/* Progress Bar (when backing up) */}
      {isCreating && (
        <section className="rounded-xl p-6 flex flex-col gap-4"
          style={{ background: A.surface, border: `1px solid ${A.border}` }}>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg" style={{ background: A.badgeBg, color: A.accent }}>
              <span className="material-symbols-outlined animate-spin text-xl">settings</span>
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold" style={{ color: A.primary }}>Đang tạo bản sao lưu...</p>
              <p className="text-xs mt-0.5" style={{ color: A.textMuted }}>{progressStage}</p>
            </div>
            <span className="text-sm font-bold" style={{ color: A.accent }}>{progress}%</span>
          </div>
          <div className="h-3 rounded-full overflow-hidden" style={{ background: A.border }}>
            <div
              className="h-full rounded-full transition-all duration-500"
              style={{ width: `${progress}%`, background: A.accent }}
            />
          </div>
        </section>
      )}

      {/* Backup List */}
      <section className="rounded-xl overflow-hidden"
        style={{ background: A.surface, border: `1px solid ${A.border}`, boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
        <div className="px-5 py-4 flex items-center justify-between"
          style={{ background: A.sidebar, borderBottom: `1px solid ${A.border}` }}>
          <h2 className="text-sm font-bold" style={{ color: A.primary }}>
            Danh sách bản sao lưu ({backups.length})
          </h2>
          <span className="text-xs" style={{ color: A.textMuted }}>
            Được sắp xếp theo ngày mới nhất
          </span>
        </div>

        <div className="divide-y" style={{ borderColor: A.border }}>
          {backups.map(b => (
            <div key={b.id}
              className="px-5 py-4 flex items-center justify-between gap-4 transition-colors"
              style={{ background: A.surface }}
              onMouseEnter={e => (e.currentTarget.style.background = A.bg)}
              onMouseLeave={e => (e.currentTarget.style.background = A.surface)}>
              <div className="flex items-center gap-4 flex-1 min-w-0">
                <div className={`p-2.5 rounded-lg shrink-0 ${b.status === 'failed' ? 'bg-red-50 text-red-600' : ''}`}
                  style={b.status !== 'failed' ? { background: A.badgeBg, color: A.accent } : {}}>
                  <span className="material-symbols-outlined text-xl">
                    {b.status === 'failed' ? 'error' : b.type === 'full' ? 'database' : 'difference'}
                  </span>
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold truncate font-mono" style={{ color: A.primary }}>{b.name}</p>
                  <div className="flex items-center gap-3 mt-0.5 flex-wrap">
                    <span className="text-xs" style={{ color: A.textMuted }}>{b.date}</span>
                    <span className="text-xs" style={{ color: A.textMuted }}>•</span>
                    <span className="text-xs font-medium" style={{ color: A.textMuted }}>{b.size}</span>
                    {b.status === 'success' && (
                      <>
                        <span className="text-xs" style={{ color: A.textMuted }}>•</span>
                        <span className="text-xs" style={{ color: A.textMuted }}>{b.tables} bảng · {b.records.toLocaleString()} bản ghi</span>
                      </>
                    )}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-3 shrink-0">
                <span className={`text-xs px-2 py-1 rounded-full font-medium ${
                  b.status === 'success' ? 'bg-emerald-50 text-emerald-700' :
                  b.status === 'failed' ? 'bg-red-50 text-red-700' :
                  'bg-amber-50 text-amber-700'
                }`}>
                  {b.status === 'success' ? 'Thành công' : b.status === 'failed' ? 'Thất bại' : 'Đang chạy'}
                </span>
                <span className="text-xs px-2 py-0.5 rounded-full"
                  style={{ background: A.bg, color: A.textMuted, border: `1px solid ${A.border}` }}>
                  {b.type === 'full' ? 'Toàn bộ' : 'Gia tăng'}
                </span>
                {b.status === 'success' && (
                  <div className="flex gap-1">
                    <button
                      onClick={() => downloadBackup(b)}
                      className="p-1.5 rounded-full transition-colors hover:opacity-70"
                      style={{ color: A.accent }}
                      title="Tải xuống">
                      <span className="material-symbols-outlined text-[18px]">download</span>
                    </button>
                    <button
                      onClick={() => setConfirmRestore(b)}
                      className="p-1.5 rounded-full transition-colors hover:opacity-70"
                      style={{ color: A.textMuted }}
                      title="Khôi phục từ bản này">
                      <span className="material-symbols-outlined text-[18px]">restore</span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* System Config Section */}
      <section className="rounded-xl p-6"
        style={{ background: A.surface, border: `1px solid ${A.border}` }}>
        <h2 className="text-base font-bold mb-4" style={{ color: A.primary }}>Cài đặt tự động sao lưu</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="p-4 rounded-lg" style={{ background: A.bg, border: `1px solid ${A.border}` }}>
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-semibold" style={{ color: A.primary }}>Sao lưu hàng ngày</p>
              <div className="w-10 h-5 rounded-full relative" style={{ background: A.accent }}>
                <span className="absolute top-0.5 right-0.5 w-4 h-4 rounded-full bg-white" />
              </div>
            </div>
            <p className="text-xs" style={{ color: A.textMuted }}>Chạy tự động lúc 23:30 mỗi ngày</p>
          </div>
          <div className="p-4 rounded-lg" style={{ background: A.bg, border: `1px solid ${A.border}` }}>
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-semibold" style={{ color: A.primary }}>Sao lưu hàng tuần</p>
              <div className="w-10 h-5 rounded-full relative" style={{ background: A.accent }}>
                <span className="absolute top-0.5 right-0.5 w-4 h-4 rounded-full bg-white" />
              </div>
            </div>
            <p className="text-xs" style={{ color: A.textMuted }}>Chủ nhật - toàn bộ dữ liệu</p>
          </div>
          <div className="p-4 rounded-lg" style={{ background: A.bg, border: `1px solid ${A.border}` }}>
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-semibold" style={{ color: A.primary }}>Giữ tối đa</p>
              <span className="text-sm font-bold" style={{ color: A.accent }}>30 bản</span>
            </div>
            <p className="text-xs" style={{ color: A.textMuted }}>Xóa bản cũ khi vượt giới hạn</p>
          </div>
        </div>
      </section>

      {/* Confirm Restore Modal */}
      {confirmRestore && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 backdrop-blur-sm"
          onClick={e => { if (e.target === e.currentTarget) setConfirmRestore(null); }}>
          <div className="w-full max-w-md rounded-2xl shadow-2xl p-6 flex flex-col gap-5 border border-[#d1c4b9]"
            style={{ background: A.surface }}>
            <div className="flex items-center gap-3">
              <div className="p-3 rounded-xl bg-amber-50">
                <span className="material-symbols-outlined text-2xl text-amber-600">warning</span>
              </div>
              <div>
                <h2 className="text-lg font-bold" style={{ color: A.primary }}>Xác nhận khôi phục</h2>
                <p className="text-xs mt-0.5" style={{ color: A.textMuted }}>Hành động này không thể hoàn tác</p>
              </div>
            </div>
            <div className="p-4 rounded-lg" style={{ background: A.bg, border: `1px solid ${A.border}` }}>
              <p className="text-xs font-semibold uppercase mb-1" style={{ color: A.textMuted }}>Bản sao lưu sẽ khôi phục</p>
              <p className="text-sm font-mono font-semibold" style={{ color: A.primary }}>{confirmRestore.name}</p>
              <p className="text-xs mt-1" style={{ color: A.textMuted }}>{confirmRestore.date} · {confirmRestore.size}</p>
            </div>
            <p className="text-sm" style={{ color: A.textMuted }}>
              Toàn bộ dữ liệu hiện tại sẽ bị <strong>ghi đè</strong> bởi dữ liệu từ bản sao lưu này.
              Hệ thống sẽ khởi động lại sau khi hoàn tất.
            </p>
            {restoring ? (
              <div className="flex items-center gap-3 p-4 rounded-lg" style={{ background: A.badgeBg }}>
                <span className="material-symbols-outlined animate-spin" style={{ color: A.accent }}>settings</span>
                <p className="text-sm font-medium" style={{ color: A.accent }}>Đang khôi phục dữ liệu...</p>
              </div>
            ) : (
              <div className="flex gap-3">
                <button onClick={() => setConfirmRestore(null)}
                  className="flex-1 py-2.5 rounded-lg text-sm font-medium border"
                  style={{ borderColor: A.border, color: A.textMuted }}>Hủy bỏ</button>
                <button onClick={doRestore}
                  className="flex-1 py-2.5 rounded-lg text-sm font-semibold text-white bg-amber-600 hover:bg-amber-700">
                  Xác nhận khôi phục
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
